### ISSUE TITLE
Some more examples

### ISSUE THREAD

**Issue by ajitam** [RomRider/divoom-timebox-evo#6]
Hello,
I'm playing whit this gadget for a past couple of days now, but with very little results.

Connection to TIMEBOX is successful.

After no luck with (more complex) examples I decided to start with `raw`.

The only visible result I can get is switching to clock

```
  var d = (new Divoom.TimeboxEvo()).createRequest('raw');
  d.push("4500");
  d.messages.forEach(m => {
    btSerial.write(Buffer.from(m.message, 'hex'), function (err, bytesWritten) {
      if (err) {
        D('send N0K', err);
      }
      else {
        D('send 0K');
      }
    })
  }) // Will display the list of messages as hexadecimals strings
  D('d.messages.asBinaryBuffer()');
  D(d.messages.asBinaryBuffer());
```

and with `4507` (not `4506`) I switch to "score board"

What would a command for setting number on score board would be?

I tried:
* `d.push("4507 0001 0002");`
* `d.push("450700 0001 0002");`
* `d.push("450700"+getScoreBoardEncoded(1,2));`

**Comment by thedull** [comment]
Not even this one is working for me. Maybe the API changed?

**Comment by ApmI00** [comment]
@thedull mybe... also it does not work for me
